#!/bin/bash
#sudo nano /usr/share/xsessions/dwm.desktop
while true; do
    xsetroot -name "$(date +"%a, %d-%b-%Y %I:%M %p")"
    sleep 30s    # atualiza a cada 30 segundos
done &
nitrogen --restore &
xdotool exec alarm-clock-applet &
sleep 0.5 &
xdotool key Alt_L+Shift_L+5 &
exec dwm 
